-- Amounts are stored as BIGINT in minor units (no floating point).

CREATE TABLE account (
    id         VARCHAR(64)              NOT NULL PRIMARY KEY,
    balance    BIGINT                   NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    -- Last line of defence: even a buggy code path cannot commit a negative balance.
    CONSTRAINT ck_account_balance_non_negative CHECK (balance >= 0)
);

-- One row per transactionId. The primary key IS the idempotency guarantee:
-- two transactions can never both commit the same id, whatever the isolation level.
CREATE TABLE balance_transaction (
    id                     VARCHAR(128)             NOT NULL PRIMARY KEY,
    type                   VARCHAR(16)              NOT NULL,
    status                 VARCHAR(16)              NOT NULL,
    source_account_id      VARCHAR(64)              REFERENCES account (id),
    destination_account_id VARCHAR(64)              REFERENCES account (id),
    amount                 BIGINT                   NOT NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_tx_amount_positive CHECK (amount > 0),
    CONSTRAINT ck_tx_type CHECK (type IN ('CREDIT', 'DEBIT', 'TRANSFER')),
    CONSTRAINT ck_tx_status CHECK (status IN ('COMPLETED', 'REJECTED'))
);

-- Double-entry style audit trail: every balance change has exactly one entry,
-- so for every account: balance = opening balance + SUM(ledger_entry.amount).
CREATE TABLE ledger_entry (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(128)             NOT NULL REFERENCES balance_transaction (id),
    account_id     VARCHAR(64)              NOT NULL REFERENCES account (id),
    amount         BIGINT                   NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_entry_amount_non_zero CHECK (amount <> 0)
);

CREATE INDEX ix_ledger_entry_account ON ledger_entry (account_id);
CREATE INDEX ix_ledger_entry_transaction ON ledger_entry (transaction_id);
